const DATA_ERROR_CODE = 400;
const EMAIL_OR_PASSWORD_ERROR_CODE = 401;
const ONLY_OWNER_ERROR_CODE = 403;
const NOT_FOUND_ERROR_CODE = 404;
const DUPLICATE_EMAIL_ERROR_CODE = 409;
const ERROR_CODE = 500;
const MONGO_DUPLICATE_ERROR_CODE = 11000;

module.exports = {
  DATA_ERROR_CODE,
  EMAIL_OR_PASSWORD_ERROR_CODE,
  ONLY_OWNER_ERROR_CODE,
  NOT_FOUND_ERROR_CODE,
  DUPLICATE_EMAIL_ERROR_CODE,
  ERROR_CODE,
  MONGO_DUPLICATE_ERROR_CODE,
};
